name: weather_app
description: Freeman Tang's Weather App.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0-163.1.beta <4.0.0"

dependencies:
  bloc: ^8.1.2
  bloc_test: ^9.1.4
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.0
  flutter_svg: ^2.0.7
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  geolocator: ^9.0.2
  get_it: ^7.6.0
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  test: ^1.24.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/weather/
    - assets/fonts/

  fonts:
    - family: Perandory
      fonts:
        - asset: assets/fonts/Perandory-Regular.otf
        - asset: assets/fonts/Perandory-Condensed.otf
          weight: 700

    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
