// Mocks generated by Mockito 5.4.2 from annotations
// in weather_app/test/infrastructure/weather/repositories/weather_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/domain/city/entities/city.dart' as _i6;
import 'package:weather_app/domain/weather/entities/weather.dart' as _i3;
import 'package:weather_app/infrastructure/weather/datasources/weather_remote_datasource.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeather_1 extends _i1.SmartFake implements _i3.Weather {
  _FakeWeather_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDataSource extends _i1.Mock
    implements _i4.WeatherRemoteDataSource {
  MockWeatherRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);
  @override
  _i5.Future<List<_i3.Weather>> getWeathers(List<_i6.City>? cities) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeathers,
          [cities],
        ),
        returnValue: _i5.Future<List<_i3.Weather>>.value(<_i3.Weather>[]),
      ) as _i5.Future<List<_i3.Weather>>);
  @override
  _i5.Future<_i3.Weather> getWeather(_i6.City? city) => (super.noSuchMethod(
        Invocation.method(
          #getWeather,
          [city],
        ),
        returnValue: _i5.Future<_i3.Weather>.value(_FakeWeather_1(
          this,
          Invocation.method(
            #getWeather,
            [city],
          ),
        )),
      ) as _i5.Future<_i3.Weather>);
}
